#!/bin/bash
# Mintain - Small bash script for Linux maintenance (updating and cleaning).
# Commands include: update, upgrade, dist-upgrade, update-grub, autoremove, autoclean, 
#                   empty-trash, clean.
# dist-upgrade will prompt (y/n), abort if not sure.


RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"
BOLD="\033[1m"


clear
echo 
echo "#######################################"
echo "#  Bash script for Linux maintenance  #"
echo "#  Updates, upgrades, and cleans-up.  #"
echo "#  Made with Linux Mint 18 (sarah)    #"
echo "#  Will work for many other distros   #"
echo "#######################################"


echo
sleep 0.5
echo "Commands include: -update" 
echo "                  -upgrade"
echo "                  -dist-upgrade"
echo "                  -update-grub"
echo "                  -autoremove"
echo "                  -autoclean" 
echo "                  -empty-trash"
echo "                  -and clean  (in that order)"
echo
echo "                  'dist-upgrade' will prompt user (y/n)"
echo "                  option to update again IF upgrades were available (prompts)"
sleep 0.5
echo
echo 
read -n 1 -s -p "Press any key to continue.. "
clear


#com1
echo
echo -e "${BOLD}Command 1: ${GREEN}update ${NOCOLOR}"
sudo apt-get update
echo

#com2
echo -e "${BOLD}Command 2: ${GREEN}upgrade ${NOCOLOR}"
sudo apt-get upgrade
echo

#com3
echo -e "${BOLD}Command 3: ${GREEN}dist-upgrade  (skip if not sure) ${NOCOLOR}"

read -p "           Run dist-upgrade? (y/n) " -n 1 -r
echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
  sudo apt-get dist-upgrade
  fi
echo

#option to update again, after upgrades (if upgrades were available)
#repeat1
echo -e "${BOLD}Re-update: ${GREEN}If upgrades were available.. ${NOCOLOR}"

read -p "           update again? (y/n) " -n 1 -r
echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
  sudo apt-get update
  fi
echo

#com4
echo -e "${BOLD}Command 4: ${GREEN}update-grub ${NOCOLOR}"
sudo update-grub2
echo

#com5
echo -e "${BOLD}Command 5: ${GREEN}autoremove ${NOCOLOR}"
sudo apt-get autoremove
echo

#com6
echo -e "${BOLD}Command 6: ${GREEN}autoclean ${NOCOLOR}"
sudo apt-get autoclean
echo

#com7
echo -e "${BOLD}Command 7: ${GREEN}empty trash ${NOCOLOR}"
sudo trash-empty
echo

#com8
echo -e "${BOLD}Command 8: ${GREEN}clean ${NOCOLOR}"
sudo apt-get clean
echo

#done
echo -e "${BOLD}      Done ${GREEN}and Done.${NOCOLOR} >>> ${BOLD}All Systems Go. ${NOCOLOR}"
echo
echo
sleep 1.5


#return prompt
echo -e "           ${GREEN}Here's your prompt.. ${NOCOLOR}"
sleep 0.5
echo
