#!/bin/bash
# Mintain - Small bash script for Linux maintenance (updating and cleaning).
# Commands include: update, upgrade, dist-upgrade, update-grub, autoremove, autoclean, 
#                   empty-trash, clean.
# dist-upgrade will prompt (y/n), abort if not sure.


RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"
BOLD="\033[1m"


clear
echo 
echo "#################################"
echo "#  Maintain your linux system   #"
echo "#  and do clean-up afterwards.  #"
echo "#  Made with/for Linux Mint 18  #"
echo "#  Will work for other distros  #"
echo "#################################"

sleep 0.5
echo 
read -n 1 -s -p "Press any key to continue.. "
clear


#com1
echo -e "${BOLD}Command 1: ${GREEN}update ${NOCOLOR}"
sudo apt-get update
echo

#com2
echo -e "${BOLD}Command 2: ${GREEN}upgrade ${NOCOLOR}"
sudo apt-get upgrade
echo

#com3
echo -e "${BOLD}Command 3: ${GREEN}dist-upgrade  (abort if not sure) ${NOCOLOR}"

read -p "           Run dist-upgrade? (y/n) " -n 1 -r
echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
  sudo apt-get dist-upgrade
  fi
echo

#com4
echo -e "${BOLD}Command 4: ${GREEN}update-grub ${NOCOLOR}"
sudo update-grub2
echo

#com5
echo -e "${BOLD}Command 5: ${GREEN}autoremove ${NOCOLOR}"
sudo apt-get autoremove
echo

#com6
echo -e "${BOLD}Command 6: ${GREEN}autoclean ${NOCOLOR}"
sudo apt-get autoclean
echo

#com7
echo -e "${BOLD}Command 7: ${GREEN}empty trash ${NOCOLOR}"
sudo trash-empty
echo

#com8
echo -e "${BOLD}Command 8: ${GREEN}clean ${NOCOLOR}"
sudo apt-get clean
echo

#done
echo -e "${BOLD}      Done ${GREEN}and Done.${NOCOLOR} >>> ${RED}All Systems Go. ${NOCOLOR}"
echo
echo
sleep 1.5


#return prompt
echo -e "           ${GREEN}Here's your prompt.. ${NOCOLOR}"
sleep 0.5
echo
